image: texlive/texlive

LuaLaTeX:
    script: 
        - latexmk -pdflua thesis.tex

XeLaTeX:
    script: 
        - latexmk -pdfxe thesis.tex

pdfLaTeX:
    script: 
        - latexmk -pdf thesis.tex
    artifacts:
        paths:
            - thesis.pdf