image: texlive/texlive

build:
    script: 
        - latexmk -pdflua thesis.tex
        - latexmk -pdfxe thesis.tex
        - latexmk -pdf thesis.tex
        - latexmk -pdfps thesis.tex
    artifacts:
        paths:
            - thesis.pdf