image: texlive/texlive:latest

LuaLaTeX:
    script: 
        - sed 's/,oneside/,twoside/' thesis.tex > thesis-twoside.tex
        - latexmk -pdflua thesis.tex
        - latexmk -pdflua thesis-twoside.tex
    artifacts:
        paths:
            - thesis.pdf
            - thesis-twoside.pdf

XeLaTeX:
    script: 
        - sed 's/,oneside/,twoside/' thesis.tex > thesis-twoside.tex
        - latexmk -pdfxe thesis.tex
        - latexmk -pdfxe thesis-twoside.tex
    artifacts:
        paths:
            - thesis.pdf
            - thesis-twoside.pdf
