image: texlive/texlive:latest

LuaLaTeX:
    script: 
        - latexmk -pdflua thesis.tex
    artifacts:
        paths:
            - thesis.pdf

XeLaTeX:
    script: 
        - latexmk -pdfxe thesis.tex
    artifacts:
        paths:
            - thesis.pdf
