# Use ./run.sh to start docker compose
services:
  texlab:
    build: .
    container_name: bc_thesis
    # Preserved files ownership
    user: ${MY_UID}:${MY_GID}
    volumes:
      - ./:${PWD}
      # Preserved files ownership
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    working_dir: ${PWD}
    tty: true

