name: LaTeX Build

on:
  push:
    branches:
      - main

jobs:
  LuaLaTeX:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build (LuaLaTeX)
        run: latexmk -pdflua thesis.tex

      - name: Build (twosided) (LuaLaTeX)
        run: |
          sed 's/,oneside/,twoside/' thesis.tex > thesis-twoside.tex
          latexmk -pdflua thesis-twoside.tex

      - name: Build Presentation (LuaLaTeX)
        run: latexmk -pdflua presentation.tex

      - name: Build G2OAT (LuaLaTeX)
        run: latexmk -pdflua g2oat.tex

        ################################################################################
      - name: Upload PDF artifact (LuaLaTeX)
        uses: actions/upload-artifact@v4
        with:
          name: thesis-lualatex
          path: thesis.pdf

      - name: Upload PDF artifact (twoside) (LuaLaTeX)
        uses: actions/upload-artifact@v4
        with:
          name: thesis-twoside-lualatex
          path: thesis-twoside.pdf

      - name: Upload PDF artifact (Presentation) (LuaLaTeX)
        uses: actions/upload-artifact@v4
        with:
          name: presentation-lualatex
          path: presentation.pdf

      - name: Upload PDF artifact (G2OAT) (LuaLaTeX)
        uses: actions/upload-artifact@v4
        with:
          name: g2oat-lualatex
          path: g2oat.pdf

  XeLaTeX:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build (XeLaTeX)
        run: latexmk -pdfxe thesis.tex

      - name: Build twosided (XeLaTeX)
        run: |
          sed 's/,oneside/,twoside/' thesis.tex > thesis-twoside.tex
          latexmk -pdfxe thesis-twoside.tex

      - name: Build Presentation (XeLaTeX)
        run: latexmk -pdfxe presentation.tex

      - name: Build G2OAT (XeLaTeX)
        run: latexmk -pdfxe g2oat.tex

        ################################################################################
      - name: Upload PDF artifact (XeLaTeX)
        uses: actions/upload-artifact@v4
        with:
          name: thesis-xelatex
          path: thesis.pdf

      - name: Upload PDF artifact (twoside) (XeLaTeX)
        uses: actions/upload-artifact@v4
        with:
          name: thesis-twoside-xelatex
          path: thesis-twoside.pdf

      - name: Upload PDF artifact (Presentation) (XeLaTeX)
        uses: actions/upload-artifact@v4
        with:
          name: presentation-xelatex
          path: presentation.pdf

      - name: Upload PDF artifact (G2OAT) (XeLaTeX)
        uses: actions/upload-artifact@v4
        with:
          name: g2oat-xelatex
          path: g2oat.pdf
